-- Autor: Ronald Garcia Guerrero
CREATE TABLE VIVIENDAS (
	ID SMALLINT NOT NULL AUTO_INCREMENT,
    TIPO ENUM('PISO','ADOSADO','CHALET','CASA') NOT NULL,
    ZONA ENUM('CENTRO','NERVION','TRIANA','ALJARAFE','MACARENA') NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    DORMITORIOS ENUM('1','2','3','4','5') NOT NULL DEFAULT '3',
    PRECIO DECIMAL(10,0) NOT NULL,
    TAMANIO DECIMAL(10,0) NOT NULL,
    EXTRAS SET('PISCINA','JARDIN','GARAJE','N/A') NOT NULL DEFAULT 'N/A',
    FOTO BLOB,
    OBSERVACIONES TEXT,
    CONSTRAINT PRIMARY KEY (ID)
);